name: Build and Push Docker Image

on:
  workflow_run:
    workflows: [Build and Test Docker Image]
    types: [completed]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }} # Ensures checkout from the triggering branch
      
      - name: Get repository and branch details
        run: |
          echo "REPO_NAME=$(basename ${{ github.repository }})" >> $GITHUB_ENV
          echo "BRANCH_NAME=${{ github.event.workflow_run.head_branch || github.ref_name }}" >> $GITHUB_ENV
          echo "REPO_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Print details
        run: |
          echo "Repository: ${{ env.REPO_NAME }}"
          echo "Branch: ${{ env.BRANCH_NAME }}"
          echo "Owner: ${{ env.REPO_OWNER }}"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build \
          -t ghcr.io/${{ env.REPO_OWNER }}/${{ env.BRANCH_NAME }}:${{ github.sha }} \
          -t ghcr.io/${{ env.REPO_OWNER }}/${{ env.BRANCH_NAME }}:latest . -f docker/Dockerfile

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ env.REPO_OWNER }}/${{ env.BRANCH_NAME }}:${{ github.sha }} &&
          docker push ghcr.io/${{ env.REPO_OWNER }}/${{ env.BRANCH_NAME }}:latest

      - name: Update README.md
        run: |
          # Replace the README section with the updated table
          sed -i '/## CI\/CD/,$d' README.md
          echo "## CI/CD" >> README.md
          echo "" >> README.md
          echo "[![Build Status](https://github.com/${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}/actions/workflows/build-and-push.yml/badge.svg?branch=$branch)](https://github.com/${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}/actions/workflows/build-and-push.yml?query=branch%3A$branch)" >> README.md
          echo "" >> README.md
  
      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          if ! git diff --quiet; then
            git add -f README.md
            git commit -m "Update modules list with badges"
            git push
          else
            echo "No changes detected, skipping commit."
          fi